// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Movies.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MoviesDbContext))]
    [Migration("20261005125656_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer")
                        .HasColumnName("genres_id");

                    b.Property<int>("MoviesId")
                        .HasColumnType("integer")
                        .HasColumnName("movies_id");

                    b.HasKey("GenresId", "MoviesId")
                        .HasName("pk_movie_genres");

                    b.HasIndex("MoviesId")
                        .HasDatabaseName("ix_movie_genres_movies_id");

                    b.ToTable("movie_genres", (string)null);
                });

            modelBuilder.Entity("Movies.Domain.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .UseCollation("und-x-icu");

                    b.Property<string>("ProfilePath")
                        .HasColumnType("text")
                        .HasColumnName("profile_path");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_name");

                    b.Property<int>("TmdbPersonId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_person_id");

                    b.HasKey("Id")
                        .HasName("pk_actors");

                    b.HasIndex("SearchName")
                        .HasDatabaseName("ix_actors_search_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TmdbPersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_actors_tmdb_person_id");

                    b.ToTable("actors", (string)null);
                });

            modelBuilder.Entity("Movies.Domain.CastMember", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<int>("BillingOrder")
                        .HasColumnType("integer")
                        .HasColumnName("billing_order");

                    b.Property<string>("Character")
                        .HasColumnType("text")
                        .HasColumnName("character");

                    b.HasKey("MovieId", "ActorId")
                        .HasName("pk_cast_members");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_cast_members_actor_id");

                    b.ToTable("cast_members", (string)null);
                });

            modelBuilder.Entity("Movies.Domain.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_name");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("Movies.Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cast_synced_at");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("original_language");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<double>("Popularity")
                        .HasColumnType("double precision")
                        .HasColumnName("popularity");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("poster_url");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("SearchTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("search_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title")
                        .UseCollation("und-x-icu");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.Property<decimal>("VoteAverage")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("vote_average");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer")
                        .HasColumnName("vote_count");

                    b.HasKey("Id")
                        .HasName("pk_movies");

                    b.HasIndex("Popularity")
                        .HasDatabaseName("ix_movies_popularity");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("ix_movies_release_date");

                    b.HasIndex("SearchTitle")
                        .HasDatabaseName("ix_movies_search_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchTitle"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchTitle"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_movies_title");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("Movies.Domain.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_genres_genres_genres_id");

                    b.HasOne("Movies.Domain.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_genres_movies_movies_id");
                });

            modelBuilder.Entity("Movies.Domain.CastMember", b =>
                {
                    b.HasOne("Movies.Domain.Actor", "Actor")
                        .WithMany("Roles")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cast_members_actors_actor_id");

                    b.HasOne("Movies.Domain.Movie", "Movie")
                        .WithMany("Cast")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cast_members_movies_movie_id");

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Movies.Domain.Actor", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Movies.Domain.Movie", b =>
                {
                    b.Navigation("Cast");
                });
#pragma warning restore 612, 618
        }
    }
}
